version: '2.2'
services:
  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:3000"

    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000 # generate via `openssl rand -hex 32`
      - NEXTAUTH_URL=http://localhost:4000
      - TELEMETRY_ENABLED=false
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false
      - LANGFUSE_INIT_ORG_ID=${LANGFUSE_INIT_ORG_ID}
      - LANGFUSE_INIT_ORG_NAME=${LANGFUSE_INIT_ORG_NAME}
      - LANGFUSE_INIT_PROJECT_ID=${LANGFUSE_INIT_PROJECT_ID}
      - LANGFUSE_INIT_PROJECT_NAME=${LANGFUSE_INIT_PROJECT_NAME}
      - LANGFUSE_INIT_PROJECT_PUBLIC_KEY=${LANGFUSE_INIT_PROJECT_PUBLIC_KEY}
      - LANGFUSE_INIT_PROJECT_SECRET_KEY=${LANGFUSE_INIT_PROJECT_SECRET_KEY}
      - LANGFUSE_INIT_USER_EMAIL=${LANGFUSE_INIT_USER_EMAIL}
      - LANGFUSE_INIT_USER_NAME=${LANGFUSE_INIT_USER_NAME}
      - LANGFUSE_INIT_USER_PASSWORD=${LANGFUSE_INIT_USER_PASSWORD}

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  # Python application
  brias_evaluation_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LANGFUSE_HOST=http://langfuse-server:3000
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_INIT_PROJECT_PUBLIC_KEY} #${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_INIT_PROJECT_SECRET_KEY} #${LANGFUSE_SECRET_KEY}
      - LANGFUSE_INIT_ORG_ID=${LANGFUSE_INIT_ORG_ID}
      - LANGFUSE_INIT_ORG_NAME=${LANGFUSE_INIT_ORG_NAME}
      - LANGFUSE_INIT_PROJECT_ID=${LANGFUSE_INIT_PROJECT_ID}
      - LANGFUSE_INIT_PROJECT_NAME=${LANGFUSE_INIT_PROJECT_NAME}
      - LANGFUSE_INIT_PROJECT_PUBLIC_KEY=${LANGFUSE_INIT_PROJECT_PUBLIC_KEY}
      - LANGFUSE_INIT_PROJECT_SECRET_KEY=${LANGFUSE_INIT_PROJECT_SECRET_KEY}
      - LANGFUSE_INIT_USER_EMAIL=${LANGFUSE_INIT_USER_EMAIL}
      - LANGFUSE_INIT_USER_NAME=${LANGFUSE_INIT_USER_NAME}
      - LANGFUSE_INIT_USER_PASSWORD=${LANGFUSE_INIT_USER_PASSWORD}
      - PORT=3030
      - LLM_MODEL_PATH=/gpt4all/Phi-3-mini-4k-instruct-q4.gguf #${LLM_MODEL_PATH}
      - DB_PATH=/data/sampled_conversations.db
    depends_on:
      - langfuse-server
    ports:
      - "4040:3030"  
    volumes:
      - ./src:/src  # Maps project files for development
      - ./src/gpt4all:/gpt4all
      - ./data:/data

volumes:
  database_data:
    driver: local

